[package]
name = "rust-http-simple"
version = "0.1.0"
edition = "2021"

[dependencies]
httparse = "1.8.0"
num_cpus = "1.16.0"
tokio = { version = "1.36.0", features = ["full"] }

[profile.lto]
inherits = "release"
lto = true
